# Generated by Django 4.1.7 on 2023-04-03 13:46

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.TextField(default=registration.models.code_generator, help_text='random code used for registration and for password reset', max_length=15)),
            ],
        ),
    ]
