# Generated by Django 4.1.7 on 2023-04-03 13:46

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Asian', 'Asian'), ('Burger', 'Burgers'), ('Chinese', 'Chinese'), ('Greek', 'Greek'), ('Healthy', 'Healthy'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Pizza', 'Pizza'), ('Poke', 'Poke'), ('Sandwich', 'Sandwich'), ('Sushi', 'Sushi'), ('Spanish', 'Spanish'), ('Vegan', 'Vegan')], max_length=50)),
                ('country', models.CharField(choices=[('AT', 'Austria'), ('CH', 'Switzerland'), ('DE', 'Germany')], max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('opening_hours', models.CharField(max_length=50)),
                ('price_level', models.CharField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$'), ('5', '$$$$$')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.restaurant_directory_path)),
            ],
        ),
    ]
