# Generated by Django 4.1.7 on 2023-04-04 08:54

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.IntegerField(choices=[(1, 'Asian'), (2, 'Burgers'), (3, 'Chinese'), (4, 'Greek'), (5, 'Healthy'), (6, 'Italian'), (7, 'Mexican'), (8, 'Pizza'), (9, 'Poke'), (10, 'Sandwich'), (11, 'Sushi'), (12, 'Spanish'), (13, 'Vegan')])),
                ('country', models.CharField(choices=[('AT', 'Austria'), ('CH', 'Switzerland'), ('DE', 'Germany')], max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('opening_hours', models.CharField(max_length=50)),
                ('price_level', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.restaurant_directory_path)),
            ],
        ),
    ]
